apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: position-tracker
  name: position-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-tracker
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-position-tracker:release3
        name: k8s-fleetman-position-tracker
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: position-tracker
  name: fleetman-position-tracker
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
  selector:
    app: position-tracker
  type: ClusterIP